---
# vars file for install_docker_server

owner                        : Alexey Becker
ansible_user                 : docker
# SSH private Key angeben
ansible_ssh_private_key_file : /keys/id_rsa